### ISSUE TITLE
1.15.2 Crash at start-up

### ISSUE THREAD

**Issue by crazystone2407** [SilentChaos512/Silent-Gear#111]
## Versions

- **Silent Gear**: 1.15.2
- **Silent's Gems**: N/A
- **Silent Lib**: N/A <apparently the issue>
- **Forge**: 1.15.2
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
start-up 

(Description here)

## Actual Behavior
start-up failed, ERROR in pre-loading phase, reporting missing lib'S

(Description here)

## Links/Images
[13:01:44] [Server thread/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §esilentgear§r requires §6silentlib§r §o4.6 or above§r
§7Currently, §6silentlib§r§7 is §o§nnot installed
        at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:63) ~[?:?] {re:classloading}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_242] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242] {}
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272) ~[?:1.8.0_242] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_242] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_242] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242] {}
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_242] {}
        at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:117) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.get(ModLoader.java:146) [?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) [?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
[13:01:44] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Mod §esilentgear§r requires §6silentlib§r §o4.6 or above§r
§7Currently, §6silentlib§r§7 is §o§nnot installed
]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:168) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
[13:01:44] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: xxx./crash-reports/crash-2020-04-11_13.01.44-server.txt

## Steps to Reproduce the Problem
each time I load the mod into the mod folder

**Comment by SilentChaos512** [comment]
[Silent Lib](https://www.curseforge.com/minecraft/mc-mods/silent-lib) is required for Silent Gear to run, as the crash report says.
