### ISSUE TITLE
Failed to reload data packs

### ISSUE THREAD

**Issue by LlubNek** [SilentChaos512/Silent-Gear#176]
## Versions
- **Silent Gear**: SilentGear-1.15.2-1.10.0+131.jar
- **Silent's Gems**: SilentGems-1.15.2-3.5.8+91.jar
- **Silent Lib**: SilentLib-1.15.2-4.6.6+59.jar
- **Forge**: 31.2.31
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Normal startup with no errors.

## Actual Behavior
Even with just the "Silent" mods, Silent Gems fails to load chaos buffs and Silent Gear fails to load materials, parts, and traits, according to the message on world join.

In the log, I find this:
```
[10:59:46] [Server thread/ERROR]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: This is not a JSON Array.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[?:1.8.0_51]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1467) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[gson-2.8.0.jar:?]
	at net.silentchaos512.gear.api.material.MaterialDisplay.deserialize(MaterialDisplay.java:73) ~[?:1.10.0+131]
	at net.silentchaos512.gear.gear.material.PartMaterial$Serializer.deserializeDisplayProps(PartMaterial.java:310) ~[?:1.10.0+131]
	at net.silentchaos512.gear.gear.material.PartMaterial$Serializer.deserialize(PartMaterial.java:234) ~[?:1.10.0+131]
	at net.silentchaos512.gear.gear.material.PartMaterial$Serializer.deserialize(PartMaterial.java:217) ~[?:1.10.0+131]
	at net.silentchaos512.gear.gear.material.MaterialSerializers.deserialize(MaterialSerializers.java:33) ~[?:1.10.0+131]
	at net.silentchaos512.gear.gear.material.MaterialManager.func_195410_a(MaterialManager.java:73) ~[?:1.10.0+131]
	...
```

## Links/Images
![image](https://user-images.githubusercontent.com/313762/87954498-72db0a80-ca7a-11ea-9078-b8020df53533.png)
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/4948558/latest.log)

## Steps to Reproduce the Problem
1. install mods
2. start minecraft
3. create new world
4. observe message and check logs

**Comment by SilentChaos512** [comment]
Caused by a change in the material file format. Will be fixed in today's update.
