### ISSUE TITLE
[1.16] Magnetic trait disconnects players.

### ISSUE THREAD

**Issue by WhitePhant0m** [SilentChaos512/Silent-Gear#180]
## Versions

- **Silent Gear**: 1.16.1-1.10.0+133
- **Silent's Gems**: N/A 
- **Silent Lib**: 1.16.1-4.7.0+58
- **Forge**: 32.0.70
- **Modpack**: ATM6 
- **Optifine Installed**: No 

## Expected Behavior

Magnetic trait not disconnecting players.

## Actual Behavior

Magnetic trait disconnects players and wont let them stay connected as long as there is an item nearby

## Steps to Reproduce the Problem

1. Be on a server
2. Have a tool with magnetic
3. Drop an item
4. Get disconnected

**Comment by Houyami** [comment]
I can confirm the reproduction of the problem. Tested on 3 worlds.

**Comment by SilentChaos512** [comment]
Anything notable in the server log? Or the client log?

**Comment by Houyami** [comment]
[21Jul2020 18:26:54.387] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /72.176.23.12:53675
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:456) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:194) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:869) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.item.ItemEntity.func_241205_ce_()Lnet/minecraft/util/math/vector/Vector3d;
	at net.silentchaos512.gear.event.GearEvents.onPlayerTick(GearEvents.java:381) ~[?:1.10.0+133]
	at net.minecraftforge.eventbus.ASMEventHandler_89_GearEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:195) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:393) ~[?:?]
	... 9 more

Is the only thing that jumps out at me, it's repeated several times in my debug log which I've uploaded as well for further dissection, all of the errors are at the bottom of the log. This is the server log, client log doesn't seem to have anything for me will reproduce and see if it yells at me
[debug-3.log](https://github.com/SilentChaos512/Silent-Gear/files/4957057/debug-3.log)

**Comment by Houyami** [comment]
Update: Singleplayer works fine, magnetic causes items to go away from the player it seems to be a server only thing from my testing.

**Comment by SilentChaos512** [comment]
Looks like the method called is client-only (#179). It seems to be the wrong method anyway. Changing it should fix both issues.
