### ISSUE TITLE
Crash when JEI tries to render distilled water canister

### ISSUE THREAD

**Issue by SquishyBBB** [SilentChaos512/Silent-Gear#395]
When I typed "wat" into jei to search for water sources, my game crashed (this happened twice). The crash report says it is due to a canister of distilled water having rendering issues? Going to hide it from jei as a temporary fix but thought you should know. 

Error:

java.lang.IncompatibleClassChangeError: Expected static method mezz.jei.color.ColorGetter.getColors(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;II)Ljava/util/List;
	at net.silentchaos512.mechanisms.util.color.ColorGetter.getColor(ColorGetter.java:34) ~[?:0.8.9+74] {re:classloading}
	at net.silentchaos512.mechanisms.util.color.ColorGetter.getColor(ColorGetter.java:26) ~[?:0.8.9+74] {re:classloading}
	at net.silentchaos512.mechanisms.init.ModItems.lambda$registerItemColors$10(ModItems.java:51) ~[?:0.8.9+74] {re:classloading}
	at net.silentchaos512.mechanisms.init.ModItems$$Lambda$19989/619615243.getColor(Unknown Source) ~[?:?] {}

Edit: This crash occurs with other canisters as well, not just water.

**Comment by SquishyBBB** [comment]
Updated the mod and it works.
