### ISSUE TITLE
Gear Items cannot be crafted on servers

### ISSUE THREAD

**Issue by chris-wjn** [SilentChaos512/Silent-Gear#453]
## Versions
<silentgear 2.6.35>
- **Silent Lib**: 4.10
- **Forge**: 36.2.9
- **Optifine Installed**: No

## Expected Behavior
item to be crafted in crafting window

(Description here)

## Actual Behavior
server console throws recalculate stats error. Root of the issue is this line:
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.func_180185_a(FF)Z
which I assume is some method in the tryRecalculateStats method

- (Link)

## Steps to Reproduce the Problem
join a server with the specified versions of silentgear/silentlib and try crafting an item.

**Comment by SilentChaos512** [comment]
Please provide a full log file.

**Comment by chris-wjn** [comment]
[09Dec2021 14:53:12.655] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 6f72f3aa-6c00-4c32-a46a-84bc2d6d7e87
[09Dec2021 14:53:12.657] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
net.minecraft.crash.ReportedException: Failed to recalculate gear properties
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:174) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:1265) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0-internal]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.func_180185_a(FF)Z
	at net.silentchaos512.gear.util.GearData.tryRecalculateStats(GearData.java:170) ~[silentgear:2.6.35]
	at net.silentchaos512.gear.util.GearData.recalculateStats(GearData.java:97) ~[silentgear:2.6.35]
	at net.silentchaos512.gear.api.item.ICoreItem.construct(ICoreItem.java:38) ~[silentgear:2.6.35]
	at net.silentchaos512.gear.crafting.recipe.ShapelessGearRecipe.func_77572_b(ShapelessGearRecipe.java:59) ~[silentgear:2.6.35]
	at net.silentchaos512.gear.crafting.recipe.ShapelessGearRecipe.func_77572_b(ShapelessGearRecipe.java:18) ~[silentgear:2.6.35]
	at net.minecraft.inventory.container.WorkbenchContainer.func_217066_a(SourceFile:70) ~[?:?]
	at net.minecraft.inventory.container.WorkbenchContainer.func_217069_a(SourceFile:80) ~[?:?]
	at net.minecraft.util.IWorldPosCallable.func_221487_a(SourceFile:35) ~[?:?]
	at net.minecraft.util.IWorldPosCallable$2.func_221484_a(SourceFile:22) ~[?:?]
	at net.minecraft.util.IWorldPosCallable.func_221486_a(SourceFile:34) ~[?:?]
	at net.minecraft.inventory.container.WorkbenchContainer.func_75130_a(SourceFile:80) ~[?:?]
	at net.minecraft.inventory.CraftingInventory.func_70299_a(SourceFile:70) ~[?:?]
	at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:61) ~[?:?]
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:219) ~[?:?]
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?]
	... 17 more

**Comment by chris-wjn** [comment]
https://pastebin.com/C8xgSvAL

**Comment by chris-wjn** [comment]
https://pastebin.com/LfzmbBUB
thats the full log, but everything apart from the actual error seems normal to me.

**Comment by chris-wjn** [comment]
I just tested the last "release" version of silentgear, and the problem does not occur on these versions.
SilentGear 2.6.30
SilentLib 4.9.6

**Comment by SilentChaos512** [comment]
Same issue as #456 and #465. Fix on the way.
