### ISSUE TITLE
CompoundMaterialItem is adding empty NBT tag to `ItemStack.EMPTY`

### ISSUE THREAD

**Issue by Buuz135** [SilentChaos512/Silent-Gear#481]
## Versions

- **Silent Gear**: 2.8.4
- **Silent's Gems**: N/A
- **Silent Lib**: 6.0.0
- **Forge**: 39.0.09
- **Modpack**: Team Rustic 4
- **Optifine Installed**: No 

While tracking a bug I figured out that some mods were adding NBT to the ItemStack.EMPTY. To do this I added some mixins to the `setTag` ItemStack method to get a trace of which mod was doing it and I got this trace:

```
Adding NBT to
1 air
{}
java.lang.Exception
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.item.ItemStack.handler$zki000$setTag(ItemStack.java:2089)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.item.ItemStack.m_41751_(ItemStack.java)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.item.ItemStack.m_41784_(ItemStack.java:521)
	at TRANSFORMER/silentgear@2.8.4/net.silentchaos512.gear.gear.material.modifier.ChargedMaterialModifier$Type.removeModifier(ChargedMaterialModifier.java:47)
	at TRANSFORMER/silentgear@2.8.4/net.silentchaos512.gear.gear.material.AbstractMaterial.removeEnhancements(AbstractMaterial.java:125)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at TRANSFORMER/silentgear@2.8.4/net.silentchaos512.gear.item.CompoundMaterialItem.create(CompoundMaterialItem.java:73)
	at TRANSFORMER/silentgear@2.8.4/net.silentchaos512.gear.item.CompoundMaterialItem.m_6787_(CompoundMaterialItem.java:155)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91271_(Minecraft.java:710)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.<init>(Minecraft.java:504)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.main.Main.main(Main.java:169)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.9/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
```

**Comment by SilentChaos512** [comment]
I wrote a similar Mixin and found two places this occurs before launch. Hopefully that's all there is. I should have an update out later today.
