### ISSUE TITLE
Server crash Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Shadowrs** [SilentChaos512/Silent-Gear#580]
## Versions

- **Silent Gear**: silent-gear-1.18.2-2.10.16
- **Silent's Gems**: N/A
- **Silent Lib**: silent-lib-1.18.2-6.2.0
- **Forge**: 40.2.0
- **Modpack**: All The Mods 7 Forge 1.18.2
- **Optifine Installed**: No

## Expected Behavior
Not crash

## Actual Behavior
Server crashes

## Links/Images
https://pastebin.com/9TeX1ui1

## Steps to Reproduce the Problem

1. Put a silent gear item in a chest with a Search button
2. Use the Search function - search for anything
3. Crash

```

java.lang.ExceptionInInitializerError: null
	at net.silentchaos512.gear.item.blueprint.GearBlueprintItem.appendSupportedTypesText(GearBlueprintItem.java:107) ~[silent-gear-1.18.2-2.10.16.jar%23313!/:2.10.16] {re:classloading}
	at net.silentchaos512.gear.item.blueprint.GearBlueprintItem.m_7373_(GearBlueprintItem.java:103) ~[silent-gear-1.18.2-2.10.16.jar%23313!/:2.10.16] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:644) ~[server-1.18.2-20220404.173914-srg.jar%23378!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:classloading,pl:accesstransformer:B,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:showcaseitem.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:A}
	at com.github.alexthe668.cloudstorage.inventory.CloudChestMenu.matchesSearch(CloudChestMenu.java:68) ~[cloudstorage-1.1.0-1.18.2.jar%2397!/:1.1.0-1.18.2] {re:classloading}
	at com.github.alexthe668.cloudstorage.inventory.CloudChestMenu.search(CloudChestMenu.java:275) ~[cloudstorage-1.1.0-1.18.2.jar%2397!/:1.1.0-1.18.2] {re:classloading}
	at com.github.alexthe668.cloudstorage.CommonProxy.processSearchPacket(CommonProxy.java:93) ~[cloudstorage-1.1.0-1.18.2.jar%2397!/:1.1.0-1.18.2] {re:classloading}
	at com.github.alexthe668.cloudstorage.network.MessageSearchCloudChest$Handler.handle(MessageSearchCloudChest.java:42) ~[cloudstorage-1.1.0-1.18.2.jar%2397!/:1.1.0-1.18.2] {re:classloading}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.silentchaos512.gear.client.KeyTracker.createKeyBinding(KeyTracker.java:46) ~[silent-gear-1.18.2-2.10.16.jar%23313!/:2.10.16] {re:classloading}
	at net.silentchaos512.gear.client.KeyTracker.<clinit>(KeyTracker.java:26) ~[silent-gear-1.18.2-2.10.16.jar%23313!/:2.10.16] {re:classloading}
	... 37 more```

**Comment by SilentChaos512** [comment]
I believe I have a fix for this issue, but I'm currently having issues with Curseforge and can't upload anything. I'll try again later.
