### ISSUE TITLE
Error accessing JEI internals

### ISSUE THREAD

**Issue by Kasia1403** [SilentChaos512/Silent-Gear#642]
[18:34:52] [Client thread/ERROR] [NotEnoughItems]: Error thrown whilst accessing JEI internals!

java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getActiveAdvancedGuiHandlers(Lnet/minecraft/client/gui/inventory/GuiContainer;)Ljava/util/List;

at codechicken.nei.jei.proxy.JEIProxy.getExtraAreas(JEIProxy.java:91) ~[JEIProxy.class:?]

at codechicken.nei.jei.proxy.JEIProxy$1.hideItemPanelSlot(JEIProxy.java:43) ~[JEIProxy$1.class:?]

at codechicken.nei.widget.ItemPanel.slotValid(ItemPanel.java:118) ~[ItemPanel.class:?]

at codechicken.nei.widget.ItemPanel.updateValidSlots(ItemPanel.java:108) ~[ItemPanel.class:?]

at codechicken.nei.widget.ItemPanel.resize(ItemPanel.java:82) ~[ItemPanel.class:?]

at codechicken.nei.layout.LayoutStyleDefault.layout(LayoutStyleDefault.java:46) ~[LayoutStyleDefault.class:?]

at codechicken.nei.LayoutManager.layout(LayoutManager.java:286) ~[LayoutManager.class:?]

at codechicken.nei.LayoutManager.load(LayoutManager.java:600) ~[LayoutManager.class:?]

at codechicken.nei.handler.NEIClientEventHandler.lambda$containerInitEvent$5(NEIClientEventHandler.java:220) ~[NEIClientEventHandler.class:?]

at java.lang.Iterable.forEach(Unknown Source) [?:1.8.0_391]

at codechicken.nei.handler.NEIClientEventHandler.containerInitEvent(NEIClientEventHandler.java:220) [NEIClientEventHandler.class:?]

at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2548_NEIClientEventHandler_containerInitEvent_Pre.invoke(.dynamic) [?:?]

at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]

at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]

at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:475) [blk.class:?]

at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1018) [bib.class:?]

at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501) [FMLClientHandler.class:?]

at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322) [FMLCommonHandler.class:?]

at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112) [FMLNetworkHandler.class:?]

at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) [aed.class:?]

at net.silentchaos512.gear.client.gui.GuiHandlerSilentGear$GuiType.open(GuiHandlerSilentGear.java:63) [GuiHandlerSilentGear$GuiType.class:?]

at net.silentchaos512.gear.item.blueprint.book.BlueprintBook.onItemRightClick(BlueprintBook.java:76) [BlueprintBook.class:?]

at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217) [aip.class:?]

at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClick(PlayerControllerMP.java:511) [bsa.class:?]

at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1597) [bib.class:?]

at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254) [bib.class:?]

at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020) [bib.class:?]

at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808) [bib.class:?]

at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]

at net.minecraft.client.Minecraft.run(Minecraft.java:5114) [bib.class:?]

at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_391]

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_391]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_391]

at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_391]

at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]

at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_391]

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_391]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_391]

at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_391]

at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]

at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]

at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]

at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by Kasia1403** [comment]
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/13492619/latest.log)

**Comment by SilentChaos512** [comment]
I have no idea. I haven't worked on 1.12.2 in ages.

**Comment by Kasia1403** [comment]
Could You please fix my issue ASAP ? JEI doesn't have RAM memory optimizations.

**Comment by SilentChaos512** [comment]
Sorry, I don't work on 1.12.2. I don't have an environment set up for it anymore, or the time to mess with it.

**Comment by Kasia1403** [comment]
@SilentChaos512 May I know why You don't have this environment setup ?
