### ISSUE TITLE
Blaze Gold 'Greedy' trait magnet effect causes crashes sporadically

### ISSUE THREAD

**Issue by Foffy123** [SilentChaos512/Silent-Gear#762]
## Versions

- **Silent Gear**: 4.0.9
- **Silent's Gems**: N/A
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.90
- **Modpack**: ATM10 2.6 
- **Optifine Installed**: No

## Expected Behavior

Not crashing -[ Issue copied from Discord](https://discord.com/channels/460182903922360349/615014589792256022/1318848182234382366) per [@SilentChaos512's request](https://discord.com/channels/460182903922360349/615014589792256022/1318929364443856999)

## Actual Behavior

Crashing

```
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.forEach(HashMap.java:1432) ~[?:?] {re:mixin}
	at TRANSFORMER/silentgear@4.0.9/net.silentchaos512.gear.core.MagnetPullTracker.onLevelTick(MagnetPullTracker.java:25) ~[silent-gear-1.21.1-neoforge-4.0.9.jar%23897!/:?] {re:classloading}
```

> 
> https://mclo.gs/CQpowHo (i have five logs that are all the same error)
> 
> So i've been having a repeated crash (MagnetPullTracker) for the past day or so on ATM10 2.6, i did digging and figured that it *seemed* to be related to the 'magnetic' trait on silentgear, it was crashing when i messed with other mods that pull items (like mobutils with the vacuum, or simple magnets)
> 
> The weird thing is that the mod author's github says that the magnetic trait is broken in 1.21 and it's a known issue, and somewhat more importantly, none of my silent gear has the 'magnetic' trait (<https://github.com/SilentChaos512/Silent-Gear/issues/697>)
> 
> I did some testing and figured out *what* is causing the crashing but not *why*, maybe someone can figure it out with this info
> 
> in the 1.21 version of silentgear used in ATM10, the 'Greedy' trait has an effect that it didn't have in 1.20/ATM9 that doesn't show in the trait description, it magnets ores and gems supposedly, though it seems to only work on gems for me ingame after testing <https://github.com/SilentChaos512/Silent-Gear/blob/1272dae868a1eb022240123daab60e1c29779657/src/generated/resources/data/silentgear/silentgear_traits/greedy.json#L13>
> 
> In my sp game, I have two blaze gold bracelets and two blaze gold rings from silent gear, which is the only material that has the greedy trait, and i confirmed that putting those in my backpack canceled the magnetism effect, i'll switch the material on my jewelry and see if i stop getting the crash (though i expect i will)
> 
> hopefully this helps someone who searches for this, i literally couldn't find anyone with this error anywhere

## Links/Images

Original log: https://mclo.gs/CQpowHo

Here are the crashes:

![image](https://github.com/user-attachments/assets/a1cfa055-d1e8-4806-a461-b98bb99f5d8f)

The only one that's different is the '-server' crash, which is here: https://mclo.gs/pvLwwNW

## Steps to Reproduce the Problem

See above, I haven't successfully reproduced it outside of my original world. Best I can tell, use blaze gold jewelry with other item 'magnet' mods, such as:

[Mob Grinding Utils](https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils)
[Simple Magnets](https://www.curseforge.com/minecraft/mc-mods/simple-magnets)
[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)

**Comment by SilentChaos512** [comment]
This should be fixed in version 4.0.11. If you still crash on the new version, please reopen with a new crash report. Thanks.
